// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class CaculatorTest
{
    private ChromeDriver driver; // Changed type from IWebDriver to ChromeDriver
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Dispose(); // Ensure driver is disposed
    }
    [Test]
    public void caculator()
    {
        driver.Navigate().GoToUrl("https://www.calculator.net/percent-calculator.html");
        driver.Manage().Window.Size = new System.Drawing.Size(866, 816);
        driver.FindElement(By.Id("cpar1")).Click();
        driver.FindElement(By.Id("cpar1")).SendKeys("36");
        driver.FindElement(By.Id("cpar2")).Click();
        driver.FindElement(By.Id("cpar2")).SendKeys("2");
        driver.FindElement(By.Name("x")).Click();
        js.ExecuteScript("window.scrollTo(0,392.79998779296875)");
        //click the calculate
        IWebElement calcuateBtn = driver.FindElement(By.XPath("//input[@type='submit' and @value='Calculate']"));
        calcuateBtn.Click();
        //wait for result
        WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.Until(d => d.FindElement(By.ClassName("verybigtext")).Displayed);
        IWebElement result = driver.FindElement(By.ClassName("verybigtext"));
        string resultText = result.Text.Trim();
        //Validate the result
        Assert.That(resultText, Is.EqualTo("36% of 2 = 0.72"), "Calculation result is Incorrect");
        Console.WriteLine("Test Passed: Percentage Calculation is correct");
    }
}
